on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Repository
      - name: Check out Repository
        uses: actions/checkout@v2
      # Install Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      # Install Python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      # Install Poetry
      - name: Install Poetry
        if: always()
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.4.0
      # Setup the Virtual Environment
      - name: Setup Virtual Environment
        if: always()
        run: |
          poetry install
          poetry shell
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
