project:
  type: website
  preview:
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: "Gregory M. Kapfhammer"
  page-navigation: true
  favicon: "favicon.png"
  open-graph: true
  site-url: https://www.gregorykapfhammer.com
  repo-url: https://github.com/gkapfham/www.gregorykapfhammer.com
  issue-url: https://github.com/gkapfham/www.gregorykapfhammer.com/issues/new
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: textbox
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Teaching"
        menu:
          - text: "Overview"
            href: teaching.md
          - text: "Data Abstraction"
            href: "https://www.proactiveprogrammers.com"
          - text: "Discrete Structures"
            href: "https://www.proactiveprogrammers.com"
      - research.qmd
      - biography.qmd
  page-footer:
    left: "Gregory M. Kapfhammer, License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: docs/faq/index.qmd
      - text: "License"
        href: license.qmd
      - text: "Trademark"
        href: trademark.qmd
    right:
      - icon: mastodon
        href: https://twitter.com/BeaMilz
      - icon: github
        href: https://github.com/beatrizmilz/
      - icon: linkedin
        href: http://www.linkedin.com/in/GregKapfhammer
      - icon: twitter
        href: https://twitter.com/BeaMilz
      - icon: envelope
        href: mailto:milz.bea@gmail.com
  twitter-card:
    creator: "@beamilz"
    card-style: summary_large_image

format:
  html:
    mainfont: IBM Plex Sans
    monofont: IBM Plex Mono
    fontsize: 1.375em
    theme:
      light:
        - united
        - united-light.scss
      dark: united-dark.scss
    css: styles.css
    code-copy: hover
    code-overflow: wrap
    code-fold: false
    code-tools: true
    highlight-style: gruvbox
    toc: true
    toc-title: "Contents"
    smooth-scroll: false
    include-in-header:
      file: js/mastodon-timeline.js
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
