project:
  type: website

website:
  title: "Gregory M. Kapfhammer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd

format:
  html:
    mainfont: IBM Plex Mono
    fontsize: 1.25em
    theme:
      light: united
      dark: theme-dark.scss
    css: styles.css
    toc: true
