project:
  type: website
  pre-render: scripts/parse-bibliography.py
  post-render: scripts/copy-files.py
  resources: _resources
  preview:
    port: 5555
    browser: false
    watch-inputs: true
    navigate: false

website:
  title: ""
  page-navigation: true
  favicon: "rocket.svg"
  open-graph: true
  site-url: https://www.gregorykapfhammer.com
  repo-url: https://github.com/gkapfham/www.gregorykapfhammer.com
  issue-url: https://github.com/gkapfham/www.gregorykapfhammer.com/issues/new
  repo-actions: [source, edit, issue]
  search:
    location: navbar
    type: textbox
  reader-mode: false
  back-to-top-navigation: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Teaching"
        menu:
          - text: "Overview"
            href: "teaching/index.qmd"
          - text: "Data Abstraction"
            href: "https://www.proactiveprogrammers.com"
          - text: "Discrete Structures"
            href: "https://www.proactiveprogrammers.com"
      - text: "Reseach"
        menu:
          - text: "Overview"
            href: research/index.qmd
          - text: "Papers"
            href: research/papers/index.qmd
          - text: "Talks"
            href: research/presentations/index.qmd
  page-footer:
    left: "{{< fa copyright >}} GMK, [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/)"
    center: '<a href="#" aria-label="Go to the top of the page">Top {{< fa circle-up >}}</a>'
    right:
      - icon: mastodon
        href: https://fosstodon.org/@gkapfham
      - icon: github
        href: https://github.com/gkapfham
      - icon: linkedin
        href: http://www.linkedin.com/in/GregKapfhammer
      - icon: google
        href: http://scholar.google.com/citations?user=g0eDPjYAAAAJ
      - icon: twitter
        href: https://twitter.com/GregKapfhammer
  twitter-card:
    creator: "@GregKapfhammer"
    card-style: summary_large_image

format:
  html:
    include-in-header:
          - text: |
              <script type="module">
                import { annotate, annotationGroup } from 'https://unpkg.com/rough-notation?module';
                const config = { type: 'underline', multiline: true, iterations: 1, strokeWidth: 4, animationDuration: 200, color: '#EF6C00' };
                // const n1 = document.querySelectorAll('.abstract .special');
                const n1 = document.querySelectorAll('.special');
                // const n1 = document.querySelector('.abstract span');
                // const a1 = annotate(n1, config);
                var al = []
                for (let i = 0; i < n1.length; i++) {
                  var newA = annotate(n1[i], config);
                  al.push(newA)
                }
                // Get the checkbox element
                var toggleButtonCheckbox = document.getElementById('toggle-button-checkbox');
                // Function to toggle the rough notation
                function toggleRoughNotation() {
                  if (toggleButtonCheckbox.checked) {
                    for (let i = 0; i < al.length; i++) {
                      var newA = al[i];
                      newA.hide();
                      newA.show();
                    }
                    // a1.hide();
                    // a1.show();
                  } else {
                    // a1.hide();
                    for (let i = 0; i < al.length; i++) {
                      var newA = al[i];
                      newA.hide();
                      // newA.show();
                    }
                  }
                }
                // Add event listener to the checkbox
                toggleButtonCheckbox.addEventListener('change', toggleRoughNotation);
              </script>
    mainfont: IBM Plex Sans
    monofont: IBM Plex Mono
    fontsize: 1.375em
    theme:
      light:
        - united
        - united-light.scss
      dark:
        - united
        - united-dark.scss
    css: styles.css
    toc: true
    toc-title: "Contents"
    code-copy: hover
    code-overflow: wrap
    # code-overflow: scroll
    code-fold: false
    code-tools: false
    highlight-style: gruvbox
    email-obfuscation: javascript
    # note: needs to be false so as to
    # ensure that the back to top button
    # in the footer of the page works correctly
    smooth-scroll: false
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
