project:
  type: website
  pre-render: scripts/parse-bibliography.py
  preview:
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: ""
  page-navigation: true
  favicon: "favicon.png"
  open-graph: true
  site-url: https://www.gregorykapfhammer.com
  repo-url: https://github.com/gkapfham/www.gregorykapfhammer.com
  issue-url: https://github.com/gkapfham/www.gregorykapfhammer.com/issues/new
  repo-actions: [source, edit, issue]
  search:
    location: navbar
    type: textbox
  reader-mode: false
  back-to-top-navigation: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Teaching"
        menu:
          - text: "Overview"
            href: teaching.qmd
          - text: "Data Abstraction"
            href: "https://www.proactiveprogrammers.com"
          - text: "Discrete Structures"
            href: "https://www.proactiveprogrammers.com"
      - text: "Reseach"
        menu:
          - text: "Overview"
            href: research.qmd
          - text: "Papers"
            href: papers.qmd
          - text: "Talks"
            href: presentations.qmd
      - research.qmd
  page-footer:
    left: "Gregory M. Kapfhammer, [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)"
    right:
      - icon: mastodon
        href: https://fosstodon.org/@gkapfham
      - icon: github
        href: https://github.com/gkapfham
      - icon: linkedin
        href: http://www.linkedin.com/in/GregKapfhammer
      - icon: google
        href: http://scholar.google.com/citations?user=g0eDPjYAAAAJ
      - icon: twitter
        href: https://twitter.com/GregKapfhammer
  twitter-card:
    creator: "@GregKapfhammer"
    card-style: summary_large_image

format:
  html:
    mainfont: IBM Plex Sans
    monofont: IBM Plex Mono
    fontsize: 1.375em
    theme:
      light:
        - united
        - united-light.scss
      dark: united-dark.scss
    css: styles.css
    toc: true
    toc-title: "Contents"
    code-copy: hover
    code-overflow: wrap
    code-fold: false
    code-tools: true
    highlight-style: gruvbox
    email-obfuscation: javascript
    smooth-scroll: false
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
