project:
  type: website
  pre-render:
    - scripts/parse-bibliography.py --force
    - scripts/minify-files.py --source _include --destination _optimize --force --verbose
  post-render:
    - scripts/minify-files.py
    - scripts/copy-files.py
  resources: _resources
  preview:
    port: 5555
    browser: false
    watch-inputs: true
    navigate: false

format:
  html:
    include-in-header:
      - file: _optimize/js/get-the-gist.js
      - file: _optimize/html/header-include.html
