project:
  type: website
  pre-render:
    - scripts/parse-bibliography.py --force
    - scripts/minify-files.py --source _include --destination _optimize --force --verbose
  post-render:
    - scripts/minify-files.py
    - scripts/copy-files.py

format:
  html:
    include-in-header:
      - file: _optimize/js/get-the-gist.js
      - file: _optimize/html/header-include.html
    include-after-body:
      - file: _include/js/instant-page.js
