- title: "International Workshop on Search-Based Software Testing"
  categories: [workshop]
  date: '2022-01-01'
  date-format: YYYY
  description: "Program Committee Member"
  year-range: "2022 - 2008"
  service-count: 12
