# Basic workflow
name: Publish

# Controls when the action will run
# Workflow begins with push or PR events
# Focuses on the master branch only
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Repository
      - name: Check out Repository
        uses: actions/checkout@v3
        with:
          submodules: true
      # Install Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      # Install Python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      # Install Poetry
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.4.0
      # Setup the Virtual Environment
      - name: Setup Virtual Environment
        run: |
          poetry install
      - name: Render and Publish
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          poetry run quarto publish netlify
